### ISSUE TITLE
bug in PRF method

### ISSUE THREAD

**Issue by cristiursachi** [Thashiznets/PWDTK.NET#1]
Inside the method:
private Byte[] PRF(Byte[] P, Byte[] S)
        {
            return _hmacsha512Obj.ComputeHash(pMergeByteArrays(P,S));
        }

it is concatenated the password and the message and this is not according with the specs. P parameter should be in fact the password for HMAC, but since HMAC it is already initialized with the password, there is not needed to pass P to your PRF method, so the PRF method should look like this:
private Byte[] PRF( Byte[] S)
        {
            return _hmacsha512Obj.ComputeHash(S);
        }

**Comment by realindiahotel** [comment]
Hello what spec for PBKDF2 are you looking at that specifies exclusive use of password purely as HMAC initialisation only? I see PRF(P, S) in the specification and yes I know that because I have initialised the HMAC with the password I could just hash the Salt, however I decided to make the function resemble what is written in the spec. Yes it goes against other implementations that do not create a PRF that works the same way, however I do not need to break compatibility with previous passwords to downgrade my code to match others.........added benefit, no rainbow tables for generic PBKDF2 can be used against my code :)

**Comment by cristiursachi** [comment]
I understand the fact of backward compatibility, it make sense to not break current apps that uses it. But since [HMAC works like this](https://en.wikipedia.org/wiki/Hash-based_message_authentication_code) : H(key ∥ H(key ∥ message)), according with your implementation, you do this: H(key ∥ H(key ∥ key ∥ message)),  so I just don't see the reason why would you double concatenate the key.

Anyway up to you to consider a bug or not.

**Comment by realindiahotel** [comment]
The reason I did that is because I wanted to match the specification here https://www.ietf.org/rfc/rfc2898.txt that specifically has PRF(P,S) and so if it means I hash a duplicate set of bytes then that's ok, it's just further key stretching as H(key ∥ H(key ∥ message)) != H(key ∥ H(key ∥ key ∥ message)) anyway. So yup I'm aware that I don't need to hash the concatenation of password + salt, but chose to do so to make it super easy for anyone looking at the specification to follow in my code, even someone who doesn't know about HMAC. So not a bug no, a design choice, and it is not any less secure as a result.
